import html2canvas from "html2canvas";
import jsPDF from "jspdf";

export interface ExportPDFOptions {
  elementId: string;
  filename?: string;
  margin?: number;
  scale?: number;
  quality?: number;
  orientation?: "portrait" | "landscape";
}

const DEFAULT_OPTIONS: Required<ExportPDFOptions> = {
  elementId: "",
  filename: "analysis-report.pdf",
  margin: 15,
  scale: 2,
  quality: 1,
  orientation: "portrait",
};

async function exportPDF(
  options: ExportPDFOptions,
): Promise<void> {
  console.log("========== PDF EXPORT START ==========");

  const config = {
    ...DEFAULT_OPTIONS,
    ...options,
  };

  console.log("Config:", config);

  const element = document.getElementById(
    config.elementId,
  );

  console.log("Target Element:", element);

  if (!element) {
    throw new Error(
      `Element "${config.elementId}" not found.`,
    );
  }

  if (
    element.offsetWidth === 0 ||
    element.offsetHeight === 0
  ) {
    throw new Error(
      "Report element is empty or hidden.",
    );
  }

  console.log("Waiting for render...");

  await new Promise((resolve) =>
    requestAnimationFrame(() => resolve(null)),
  );

  console.log("Creating Canvas...");

  const canvas = await html2canvas(element, {
    backgroundColor: "#ffffff",
    scale: config.scale,
    useCORS: true,
    allowTaint: false,
    logging: true,
    imageTimeout: 0,
    windowWidth: element.scrollWidth,
    windowHeight: element.scrollHeight,
    scrollX: 0,
    scrollY: -window.scrollY,
  });

  console.log(
    "Canvas Created:",
    canvas.width,
    canvas.height,
  );

  const imageData = canvas.toDataURL(
    "image/png",
    config.quality,
  );

  console.log("Image Generated");

  const pdf = new jsPDF({
    orientation: config.orientation,
    unit: "mm",
    format: "a4",
    compress: true,
  });

  console.log("PDF Object Created");

  const pageWidth =
    pdf.internal.pageSize.getWidth();

  const pageHeight =
    pdf.internal.pageSize.getHeight();

  const printableWidth =
    pageWidth - config.margin * 2;

  const printableHeight =
    pageHeight - config.margin * 2;

  const imageWidth = printableWidth;

  const imageHeight =
    (canvas.height * printableWidth) /
    canvas.width;

  let remainingHeight = imageHeight;

  let positionY = config.margin;

  console.log("Adding First Page");

  pdf.addImage(
    imageData,
    "PNG",
    config.margin,
    positionY,
    imageWidth,
    imageHeight,
    undefined,
    "FAST",
  );

  remainingHeight -= printableHeight;

  while (remainingHeight > 0) {
    console.log("Adding Extra Page");

    pdf.addPage();

    positionY =
      config.margin -
      (imageHeight - remainingHeight);

    pdf.addImage(
      imageData,
      "PNG",
      config.margin,
      positionY,
      imageWidth,
      imageHeight,
      undefined,
      "FAST",
    );

    remainingHeight -= printableHeight;
  }

  const totalPages = pdf.getNumberOfPages();

  console.log("Total Pages:", totalPages);

  for (
    let page = 1;
    page <= totalPages;
    page++
  ) {
    pdf.setPage(page);

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(9);
    pdf.setTextColor(120);

    pdf.text(
      "Generated by AI Data Analyst Agent",
      config.margin,
      pageHeight - 6,
    );

    pdf.text(
      `Page ${page} of ${totalPages}`,
      pageWidth - config.margin,
      pageHeight - 6,
      {
        align: "right",
      },
    );
  }

  console.log("Saving PDF...");

  pdf.save(config.filename);

  console.log("PDF Saved Successfully");

  console.log("========== PDF EXPORT END ==========");
}
export { exportPDF };