from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

from app.services.ai_insights_service import generate_ai_insights


def generate_report():

    insights = generate_ai_insights()

    filename = "AI_Data_Analyst_Report.pdf"

    document = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    # =====================================
    # REPORT TITLE
    # =====================================

    story.append(
        Paragraph(
            "AI DATA ANALYST REPORT",
            styles["Title"]
        )
    )

    story.append(Spacer(1, 15))

    story.append(
        Paragraph(
            "<b>Generated By:</b> AI Data Analyst Agent",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            "<b>Developer:</b> Pritiranjan Rout",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            "<b>Version:</b> 1.0.0",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 20))

    # =====================================
    # DATASET SUMMARY
    # =====================================

    story.append(
        Paragraph(
            "Dataset Summary",
            styles["Heading2"]
        )
    )

    table_data = [
        ["Metric", "Value"],
        ["Rows", insights["dataset_summary"]["rows"]],
        ["Columns", insights["dataset_summary"]["columns"]],
        ["Health Score", f"{insights['health_score']} %"],
        ["Duplicate Rows", insights["duplicate_rows"]]
    ]

    table = Table(table_data, colWidths=[220, 220])

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
        ])
    )

    story.append(table)

    story.append(Spacer(1, 20))

    # =====================================
    # HEALTH SCORE
    # =====================================

    story.append(
        Paragraph(
            f"<b>Dataset Health Score:</b> {insights['health_score']}%",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 20))
    # MISSING VALUES
    story.append(
    Paragraph(
        "Missing Values Analysis",
        styles["Heading2"]
    )
)
    missing_table = [["Column", "Missing Values"]]

    for column, value in insights["missing_values"].items():
        missing_table.append([column, str(value)])

    table = Table(missing_table, colWidths=[220, 220])
    table.setStyle(
    TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.darkgreen),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 1, colors.black),
        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
    ])
)
    story.append(table)

    story.append(Spacer(1, 20))
# =====================================
# OUTLIER ANALYSIS
# =====================================

    story.append(
        Paragraph(
        "   Outlier Analysis",
            styles["Heading2"]
        )
    )

    outlier_table = [["Column", "Outliers"]]

    for column, value in insights["outliers"].items():
        outlier_table.append([column, str(value)])

    table = Table(outlier_table, colWidths=[220, 220])

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.orange),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
        ])
    )

    story.append(table)

    story.append(Spacer(1, 20))
                 
# =====================================
# STRONG CORRELATION ANALYSIS
# =====================================

    story.append(
        Paragraph(
            "Strong Correlation Analysis",
            styles["Heading2"]
        )
    )

    correlation_table = [["Column 1", "Column 2", "Correlation"]]

    if insights["strong_correlations"]:

        for item in insights["strong_correlations"]:

            correlation_table.append([
                item["column_1"],
                item["column_2"],
                str(item["correlation"])
            ])

    else:

        correlation_table.append([
            "No Strong Correlation Found",
            "-",
            "-"
        ])

    table = Table(correlation_table, colWidths=[160, 160, 120])

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.darkred),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
        ])
    )

    story.append(table)

    story.append(Spacer(1, 20))
# =====================================
# AI RECOMMENDATIONS
# =====================================

    story.append(
        Paragraph(
            "AI Recommendations",
            styles["Heading2"]
        )
    )

    for recommendation in insights["recommendations"]:

        story.append(
            Paragraph(
                f"• {recommendation}",
                styles["BodyText"]
            )
        )

    story.append(Spacer(1, 20))
    story.append(
    Paragraph(
        "<br/><br/><b>Generated by AI Data Analyst Agent</b>",
        styles["Heading3"]
    )
)
    story.append(
    Paragraph(
        "Developed by Pritiranjan Rout",
        styles["BodyText"]
    )
)
    document.build(story)

    return {
        "success": True,
        "message": "PDF Report Generated Successfully",
        "report": filename
    }