import os
from datetime import datetime

from fastapi.responses import FileResponse

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image,
)
from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle,
)
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch

from app.services.ai_insights_service import generate_ai_insights


# =====================================================
# PAGE HEADER & FOOTER
# =====================================================

def add_page_number(canvas, doc):
    canvas.saveState()

    # Header
    canvas.setFont("Helvetica-Bold", 10)
    canvas.drawString(
        inch,
        11 * inch,
        "AI Data Analyst Agent"
    )

    # Footer Left
    canvas.setFont("Helvetica", 9)
    canvas.drawString(
        inch,
        0.5 * inch,
        "Developed by Pritiranjan Rout"
    )

    # Footer Center
    canvas.drawCentredString(
        4.25 * inch,
        0.5 * inch,
        datetime.now().strftime("%d-%m-%Y")
    )

    # Footer Right
    canvas.drawRightString(
        7.5 * inch,
        0.5 * inch,
        f"Page {doc.page}"
    )

    canvas.restoreState()


# =====================================================
# GENERATE REPORT
# =====================================================

def generate_report():

    insights = generate_ai_insights()

    REPORT_FOLDER = "reports"
    os.makedirs(REPORT_FOLDER, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    filename = os.path.join(
        REPORT_FOLDER,
        f"AI_Data_Analyst_Report_{timestamp}.pdf"
    )

    document = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=28,
        alignment=TA_CENTER,
        textColor=colors.darkblue,
        spaceAfter=20,
    )

    section_style = ParagraphStyle(
        "SectionTitle",
        parent=styles["Heading2"],
        fontSize=16,
        textColor=colors.darkblue,
        spaceBefore=12,
        spaceAfter=8,
    )

    story = []

    # =====================================================
    # LOGO
    # =====================================================

    logo_path = os.path.join(
        "assets",
        "logo.png"
    )

    if os.path.exists(logo_path):

        logo = Image(
            logo_path,
            width=1.5 * inch,
            height=1.5 * inch
        )

        logo.hAlign = "CENTER"

        story.append(logo)

    story.append(Spacer(1, 20))

    # =====================================================
    # COVER PAGE
    # =====================================================

    story.append(
        Paragraph(
            "AI DATA ANALYST AGENT",
            title_style
        )
    )

    story.append(
        Paragraph(
            "<para align='center'>Professional Data Analysis Report</para>",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 25))

    story.append(
        Paragraph(
            f"<b>Generated On:</b> {datetime.now().strftime('%d %B %Y %I:%M %p')}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            "<b>Generated By:</b> AI Data Analyst Agent",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            "<b>Developer:</b> Pritiranjan Rout",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            "<b>Version:</b> 1.0.0",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "<para align='center'><font color='grey'>Powered by Python • FastAPI • Pandas • Seaborn • ReportLab</font></para>",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 25))

    # =====================================================
    # REPORT INFORMATION
    # =====================================================

    story.append(
        Paragraph(
            "Report Information",
            section_style
        )
    )

    metadata = [
        ["Property", "Value"],
        ["Generated On", datetime.now().strftime("%d %B %Y %I:%M %p")],
        ["Generated By", "AI Data Analyst Agent"],
        ["Developer", "Pritiranjan Rout"],
        ["Version", "1.0.0"],
        ["Report Type", "Automated Data Analysis Report"],
    ]

    metadata_table = Table(
        metadata,
        colWidths=[180, 260]
    )

    metadata_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
        ])
    )

    story.append(metadata_table)

    story.append(Spacer(1, 25))
        # =====================================================
    # DATASET SUMMARY
    # =====================================================

    story.append(
        Paragraph(
            "Dataset Summary",
            section_style
        )
    )

    table_data = [
        ["Metric", "Value"],
        ["Rows", insights["dataset_summary"]["rows"]],
        ["Columns", insights["dataset_summary"]["columns"]],
        ["Health Score", f"{insights['health_score']} %"],
        ["Duplicate Rows", insights["duplicate_rows"]]
    ]

    table = Table(table_data, colWidths=[220, 220])

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
        ])
    )

    story.append(table)
    story.append(Spacer(1, 20))

    # =====================================================
    # HEALTH SCORE
    # =====================================================

    story.append(
        Paragraph(
            f"Dataset Health Score: {insights['health_score']}%",
            section_style
        )
    )

    story.append(Spacer(1, 20))

    # =====================================================
    # MISSING VALUES
    # =====================================================

    story.append(
        Paragraph(
            "Missing Values Analysis",
            section_style
        )
    )

    missing_table = [["Column", "Missing Values"]]

    for column, value in insights["missing_values"].items():
        missing_table.append([column, str(value)])

    table = Table(missing_table, colWidths=[220, 220])

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.darkgreen),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ])
    )

    story.append(table)
    story.append(Spacer(1, 20))

    # =====================================================
    # HISTOGRAM
    # =====================================================

    story.append(
        Paragraph(
            "Histogram",
            section_style
        )
    )

    histogram_path = os.path.join("charts", "histogram.png")

    if os.path.exists(histogram_path):
        story.append(
            Image(
                histogram_path,
                width=6 * inch,
                height=4 * inch
            )
        )

    story.append(Spacer(1, 20))

    # =====================================================
    # BOX PLOT
    # =====================================================

    story.append(
        Paragraph(
            "Box Plot",
            section_style
        )
    )

    boxplot_path = os.path.join("charts", "box_plot.png")

    if os.path.exists(boxplot_path):
        story.append(
            Image(
                boxplot_path,
                width=6 * inch,
                height=4 * inch
            )
        )

    story.append(Spacer(1, 20))

    # =====================================================
    # CORRELATION HEATMAP
    # =====================================================

    story.append(
        Paragraph(
            "Correlation Heatmap",
            section_style
        )
    )

    heatmap_path = os.path.join(
        "charts",
        "correlation_heatmap.png"
    )

    if os.path.exists(heatmap_path):
        story.append(
            Image(
                heatmap_path,
                width=6 * inch,
                height=5 * inch
            )
        )

    story.append(Spacer(1, 20))

    # =====================================================
    # PIE CHART
    # =====================================================

    story.append(
        Paragraph(
            "Pie Chart",
            section_style
        )
    )

    pie_path = os.path.join(
        "charts",
        "pie_chart.png"
    )

    if os.path.exists(pie_path):
        story.append(
            Image(
                pie_path,
                width=5 * inch,
                height=5 * inch
            )
        )

    story.append(Spacer(1, 20))

    # =====================================================
    # COUNT PLOT
    # =====================================================

    story.append(
        Paragraph(
            "Count Plot",
            section_style
        )
    )

    count_path = os.path.join(
        "charts",
        "count_plot.png"
    )

    if os.path.exists(count_path):
        story.append(
            Image(
                count_path,
                width=6 * inch,
                height=4 * inch
            )
        )

    story.append(Spacer(1, 20))
        # =====================================================
    # OUTLIER ANALYSIS
    # =====================================================

    story.append(
        Paragraph(
            "Outlier Analysis",
            section_style
        )
    )

    outlier_table = [["Column", "Outliers"]]

    for column, value in insights["outliers"].items():
        outlier_table.append([column, str(value)])

    table = Table(outlier_table, colWidths=[220, 220])

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.orange),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ])
    )

    story.append(table)
    story.append(Spacer(1, 20))

    # =====================================================
    # STRONG CORRELATION ANALYSIS
    # =====================================================

    story.append(
        Paragraph(
            "Strong Correlation Analysis",
            section_style
        )
    )

    correlation_table = [["Column 1", "Column 2", "Correlation"]]

    if insights["strong_correlations"]:
        for item in insights["strong_correlations"]:
            correlation_table.append([
                item["column_1"],
                item["column_2"],
                str(item["correlation"])
            ])
    else:
        correlation_table.append([
            "No Strong Correlation Found",
            "-",
            "-"
        ])

    table = Table(correlation_table, colWidths=[160, 160, 120])

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.darkred),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ])
    )

    story.append(table)
    story.append(Spacer(1, 20))

    # =====================================================
    # AI RECOMMENDATIONS
    # =====================================================

    story.append(
        Paragraph(
            "AI Recommendations",
            section_style
        )
    )

    for recommendation in insights["recommendations"]:
        story.append(
            Paragraph(
                f"-{recommendation}",
                styles["BodyText"]
            )
        )
    story.append(Spacer(1, 25))

    story.append(
        Paragraph(
            "<b>AI Data Analyst Agent</b>",
            styles["Heading3"]
        )
    )

    story.append(
        Paragraph(
            "Version 1.0.0",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            "© 2026 Pritiranjan Rout",
            styles["BodyText"]
        )
    )

    document.build(
        story,
        onFirstPage=add_page_number,
        onLaterPages=add_page_number
    )

    return {
        "success": True,
        "message": "PDF Report Generated Successfully",
        "report": os.path.basename(filename)
    }


# =====================================================
# LIST REPORTS
# =====================================================

def list_reports():

    REPORT_FOLDER = "reports"

    if not os.path.exists(REPORT_FOLDER):
        return {
            "success": False,
            "message": "No reports folder found."
        }

    reports = sorted(
        [
            file
            for file in os.listdir(REPORT_FOLDER)
            if file.endswith(".pdf")
        ],
        reverse=True
    )

    return {
        "success": True,
        "total_reports": len(reports),
        "reports": reports
    }


# =====================================================
# DOWNLOAD REPORT
# =====================================================

def download_report(filename):

    file_path = os.path.join("reports", filename)

    if not os.path.exists(file_path):
        return {
            "success": False,
            "message": "Report not found."
        }

    return FileResponse(
        path=file_path,
        media_type="application/pdf",
        filename=filename
    )


# =====================================================
# DELETE REPORT
# =====================================================

def delete_report(filename):

    file_path = os.path.join("reports", filename)

    if not os.path.exists(file_path):
        return {
            "success": False,
            "message": "Report not found."
        }

    os.remove(file_path)

    return {
        "success": True,
        "message": f"{filename} deleted successfully."
    }