from datetime import datetime

from reportlab.platypus import (
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from reportlab.lib import colors

from app.report.styles import (
    TITLE_STYLE,
    SECTION_STYLE,
    NORMAL_STYLE,
)

from app.report.helpers import add_section_header


def add_report_metadata(story):

    add_section_header(
        story,
        "REPORT INFORMATION"
    )

    table_data = [
        ["Property", "Value"],
        ["Generated By", "AI Data Analyst Agent"],
        ["Developer", "Pritiranjan Rout"],
        ["Version", "2.0.0"],
        ["Generated On", datetime.now().strftime("%d %B %Y %I:%M %p")],
    ]

    table = Table(
        table_data,
        colWidths=[180, 260]
    )

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
        ])
    )

    story.append(table)
    story.append(Spacer(1, 20))