import {
  Award,
  Brain,
  CheckCircle2,
  Star,
  Trophy,
} from "lucide-react";

import type { ModelCard } from "../../engine/modelCards/types";

interface Props {
  cards: ModelCard[];
}

export default function ModelRecommendationCards({
  cards,
}: Props) {
  const suitabilityColor = (
    suitability: ModelCard["suitability"]
  ) => {
    switch (suitability) {
      case "Excellent":
        return "bg-green-100 text-green-700";
      case "Good":
        return "bg-blue-100 text-blue-700";
      default:
        return "bg-yellow-100 text-yellow-700";
    }
  };

  return (
    <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
      <div className="mb-6 flex items-center gap-3">
        <Brain className="h-7 w-7 text-indigo-600" />

        <div>
          <h2 className="text-xl font-bold text-slate-900">
            AI Model Recommendations
          </h2>

          <p className="text-sm text-slate-500">
            Ranked machine learning models generated by the AI analysis engine
          </p>
        </div>
      </div>

      <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
        {cards.map((card) => (
          <div
            key={card.name}
            className="rounded-xl border border-slate-200 p-5 transition-all duration-300 hover:-translate-y-1 hover:shadow-lg"
          >
            <div className="mb-4 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Trophy className="h-6 w-6 text-amber-500" />

                <span className="text-lg font-bold">
                  #{card.rank}
                </span>
              </div>

              {card.recommended && (
                <CheckCircle2 className="h-6 w-6 text-green-600" />
              )}
            </div>

            <h3 className="mb-2 text-lg font-bold text-slate-900">
              {card.name}
            </h3>

            <div className="mb-4 flex items-center gap-2">
              <Award className="h-5 w-5 text-indigo-600" />

              <span className="font-semibold">
                {card.score}/100
              </span>
            </div>

            <div className="mb-4">
              <div className="mb-1 flex justify-between text-sm">
                <span>Confidence</span>

                <span>{card.confidence}%</span>
              </div>

              <div className="h-2 rounded-full bg-slate-200">
                <div
                  className="h-2 rounded-full bg-indigo-600"
                  style={{
                    width: `${card.confidence}%`,
                  }}
                />
              </div>
            </div>

            <div className="mb-4 flex flex-wrap gap-2">
              <span
                className={`rounded-full px-3 py-1 text-xs font-semibold ${suitabilityColor(
                  card.suitability
                )}`}
              >
                {card.suitability}
              </span>

              {card.recommended && (
                <span className="rounded-full bg-green-100 px-3 py-1 text-xs font-semibold text-green-700">
                  Recommended
                </span>
              )}
            </div>

            <div className="mb-4">
              <h4 className="mb-1 text-sm font-semibold text-slate-900">
                Best For
              </h4>

              <p className="text-sm text-slate-600">
                {card.bestFor}
              </p>
            </div>

            <div>
              <h4 className="mb-1 text-sm font-semibold text-slate-900">
                AI Explanation
              </h4>

              <p className="text-sm leading-6 text-slate-600">
                {card.reason}
              </p>
            </div>

            <div className="mt-5 flex">
              {[1, 2, 3, 4, 5].map((star) => (
                <Star
                  key={star}
                  className={`h-5 w-5 ${
                    star <= Math.round(card.score / 20)
                      ? "fill-yellow-400 text-yellow-400"
                      : "text-slate-300"
                  }`}
                />
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}