from reportlab.lib.colors import HexColor
from reportlab.lib.units import inch
from reportlab.pdfbase.pdfmetrics import stringWidth


class PageTemplate:

    @staticmethod
    def draw(canvas, doc):

        canvas.saveState()

        width = doc.pagesize[0]
        height = doc.pagesize[1]

        # =====================================
        # HEADER
        # =====================================

        canvas.setStrokeColor(HexColor("#D9D9D9"))
        canvas.setLineWidth(0.5)

        canvas.line(
            40,
            height - 45,
            width - 40,
            height - 45
        )

        canvas.setFont(
            "Helvetica-Bold",
            12
        )

        canvas.drawString(
            45,
            height - 30,
            "AI DATA ANALYST AGENT"
        )

        canvas.setFont(
            "Helvetica",
            9
        )

        canvas.drawRightString(
            width - 45,
            height - 30,
            "Professional Analytics Report"
        )

        # =====================================
        # FOOTER
        # =====================================

        canvas.line(
            40,
            40,
            width - 40,
            40
        )

        canvas.setFont(
            "Helvetica",
            8
        )

        canvas.drawString(
            45,
            25,
            "Generated by AI Data Analyst Agent v2.0.0"
        )

        page = f"Page {doc.page}"

        canvas.drawRightString(
            width - 45,
            25,
            page
        )

        canvas.restoreState()