import html2canvas from "html2canvas";
import type { ExportFormat } from "../../types/export";

import { exportCSV } from "./exporters/csv";
import { exportExcel } from "./exporters/excel";
import { exportPDF } from "../../utils/pdf/exportPDF";
import { toast } from "sonner";

export interface ExportRequest {
  format: ExportFormat;
  fileName: string;
  data?: unknown;
  element?: HTMLElement | null;
}

class ExportService {
  static async export(
    request: ExportRequest,
  ): Promise<void> {
    toast.info(`Generating ${request.format.toUpperCase()} file...`);
    switch (request.format) {
      case "csv":
        return this.exportCSV(request);

      case "excel":
        return this.exportExcel(request);

      case "pdf":
        return this.exportPDF(request);

      case "png":
        return this.exportPNG(request);

      case "markdown":
        return this.exportMarkdown(request);

      default:
        throw new Error(
          `Unsupported export format: ${request.format}`,
        );
    }
  }

  private static async exportCSV(
    request: ExportRequest,
  ): Promise<void> {
    await exportCSV({
      fileName: request.fileName,
      data: (request.data ?? []) as Record<
        string,
        unknown
      >[],
    });
    toast.success("CSV file downloaded!");
  }

  private static async exportExcel(
    request: ExportRequest,
  ): Promise<void> {
    await exportExcel({
      fileName: request.fileName,
      sheets: (request.data ?? []) as {
        name: string;
        data: Record<string, unknown>[];
      }[],
    });
    toast.success("Excel Workbook downloaded!");
  }

  private static async exportPDF(
    request: ExportRequest,
  ): Promise<void> {
    await exportPDF({
      elementId: "analysis-report",
      filename: `${request.fileName}.pdf`,
    });
    toast.success("PDF Report downloaded!");
  }

  private static async exportPNG(
    request: ExportRequest,
  ): Promise<void> {
    const el = document.getElementById("analysis-report") || document.body;
    const canvas = await html2canvas(el, {
      backgroundColor: "#ffffff",
      scale: 2,
      useCORS: true,
      logging: false,
    });
    const link = document.createElement("a");
    link.download = `${request.fileName}.png`;
    link.href = canvas.toDataURL("image/png");
    link.click();
    toast.success("PNG image snapshot downloaded!");
  }

  private static async exportMarkdown(
    request: ExportRequest,
  ): Promise<void> {
    const mdContent = `# ${request.fileName}\n\n*Generated by AI Data Analyst Agent*\n\n## Executive Analytics Report\n\n- Date: ${new Date().toLocaleDateString()}\n- Status: Production Ready\n\n### Report Summary\nExecutive analytics report generated using AI-assisted statistical profiling, correlation matrices, categorical distribution analysis, and machine learning readiness evaluation.\n`;
    const blob = new Blob([mdContent], { type: "text/markdown;charset=utf-8;" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = `${request.fileName}.md`;
    link.click();
    toast.success("Markdown report downloaded!");
  }
}

export default ExportService;